# Mini-Batch gradient descent | Type of Gradient Descent

In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [3]:
X,y = load_diabetes(return_X_y=True)

In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [5]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [18]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [19]:
reg.intercept_

151.88331005254167

In [6]:
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.4399338661568968

In [7]:
import random

class MBGDRegressor:
    
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            
            for j in range(int(X_train.shape[0]/self.batch_size)):
                
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                #print("Shape of y_hat",y_hat.shape)
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [8]:
mbgd = MBGDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=100)

In [9]:
mbgd.fit(X_train,y_train)

150.00581246608797 [  39.50505934 -143.3797737   454.41579002  305.09734071  -25.12633323
  -87.80603043 -197.41622254  115.90072849  403.52189881  110.26266976]


In [11]:
y_pred = mbgd.predict(X_test)

In [12]:
r2_score(y_test,y_pred)

0.45281703954055474

### Using sklearn

In [13]:
from sklearn.linear_model import SGDRegressor

In [14]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)

In [15]:
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])

In [16]:
y_pred = sgd.predict(X_test)

In [17]:
r2_score(y_test,y_pred)

0.4302174601099996

In [20]:
sgd.coef_

array([  45.00879925,  -81.34912851,  357.43074437,  232.8752044 ,
         25.83982006,  -15.83747102, -160.3167407 ,  126.73199698,
        307.47258905,  122.83120583])

In [21]:
sgd.intercept_

array([157.89938367])