# Classification metrics | Accuracy and Confusion

In [10]:
import numpy as np
import pandas as pd

In [11]:
df = pd.read_csv('heart.csv')

In [12]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [14]:
X= df.drop('target', axis=1)
y = df['target']

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test, y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state=42)

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [18]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [19]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [20]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [22]:
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))


Accuracy of Logistic Regression 0.7853658536585366
Accuracy of Decision Trees 0.9853658536585366


In [23]:
confusion_matrix(y_test,y_pred1)

array([[71, 31],
       [13, 90]], dtype=int64)

In [24]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



0   1
0  71  31
1  13  90

In [25]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix



0    1
0  102    0
1    3  100

In [26]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [27]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [28]:

print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  71  31
1  13  90
--------------------------------------------------
Precision -  0.743801652892562
Recall -  0.8737864077669902
F1 score -  0.8035714285714286


In [29]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
     0    1
0  102    0
1    3  100
--------------------------------------------------
Precision -  1.0
Recall -  0.970873786407767
F1 score -  0.9852216748768473


In [33]:
precision_score(y_test,y_pred1, average=None)

array([0.8452381 , 0.74380165])

In [34]:
precision_score(y_test,y_pred2, average=None)

array([0.97142857, 1.        ])

In [35]:
recall_score(y_test,y_pred2, average=None)

array([1.        , 0.97087379])